### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by PureTryOut** [andlo/auto-volume-skill#25]
Hey, thanks for this skill!

I've been packaging Mycroft for Alpine Linux (which I think is the first distribution to do so) and am currently packaging all the different skills available. The idea is to make all skills available as distro packages and not use the current Mycroft marketplace and Pip to install them. I'd love to package your skill as well, but it seems the last release has been a while ago.

Would you consider making a new release, and possibly in the future make new releases more often?

**Comment by andlo** [comment]
Hi sorry fr the not answerin :) But here I am

I hassnt made any new release, as there isnt anything new to make. Any ideas for what should be made different or added ?

**Comment by PureTryOut** [comment]
Well since the last release (before the one you just made) there have been quite a lot of commits, so I'd definitely say that warrants a new release at some point :wink: 

Thanks for making a new one! I don't have any suggestions sorry, but thanks for making this skill!

**Comment by andlo** [comment]
Yah I saw that just when I send the message :)
